- hosts: terraform-ansible
  become: true
  tasks:
    - name: instalar python3 e virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
    
    - name: instalando dependÃªncias com pip
      pip:
        virtualenv: /home/ubuntu/venv
        name:
          - django
          - djangorestframework
    
    - name: iniciando projeto django
      shell: '. /home/ubuntu/venv/bin/activate; django-admin startproject setup /home/ubuntu'
    
    - name: alterando hosts do settings.py
      lineinfile:
        path: /home/ubuntu/setup/settings.py  # <-- Corrigido o caminho
        regexp: '^ALLOWED_HOSTS'
        line: "ALLOWED_HOSTS = ['*']"
        backrefs: yes
